version: '3.2'

services:
  db:
    build: ./mssql-docker/
    image: mcmoe/mssqldocker:v2017.CU20.0
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Ctsshop@db
      MSSQL_DB: ctsshop
    networks:
      - user-mssql
#      MSSQL_USER: testuser
#      MSSQL_PASSWORD: testpass
    ports:
      - "1433:1433"
    container_name: mssql-container
  service-registry:
    build: ./service-registry
    image: ctsshop/service-registry-1.0.jar:v1.0
    container_name: service-registry
    depends_on:
      - db
    ports:
    - "8180:8180"
    networks:
      - user-mssql
  cataloge-service:
    build: ./catalogue-service/
    image: ctsshop/catalogue-service-1.0.jar:v1.0
    container_name: catalogue-service
    depends_on:
      - db
      - service-registry
    networks:
      - user-mssql
    ports:
    - "8181:8181"
  customer-service:
    build: ./customer-service/
    image: ctsshop/customer-service-1.0.jar:v1.0
    container_name: customer-service
    depends_on:
      - db
      - service-registry
    networks:
      - user-mssql
    ports:
    - "8182:8182"
  image-service:
    build: ./image-service/
    image: ctsshop/image-service-1.0.jar:v1.0
    container_name: image-service
    depends_on:
      - db
      - service-registry
    networks:
      - user-mssql
    ports:
    - "8183:8183"
  payment-service:
    build: ./payment-service/
    image: ctsshop/payment-service-1.0.jar:v1.0
    container_name: payment-service
    depends_on:
      - db
      - service-registry
    networks:
      - user-mssql
    ports:
    - "8184:8184"

networks:
  user-mssql: